### PR TITLE
Add back util for testing versioned validation

### PR DESCRIPTION
**Pull request by jpbetz**

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Patched it into my tree:

```
staging/src/k8s.io/apimachinery/pkg/runtime/testing/validation.go:73:52: not enough arguments in call to legacyscheme.Scheme.Validate
	have ("k8s.io/apimachinery/pkg/runtime".Object, []string)
	want (sets.Set[string], "k8s.io/apimachinery/pkg/runtime".Object, ...string)
staging/src/k8s.io/apimachinery/pkg/runtime/testing/validation.go:113:75: not enough arguments in call to legacyscheme.Scheme.ValidateUpdate
	have ("k8s.io/apimachinery/pkg/runtime".Object, "k8s.io/apimachinery/pkg/runtime".Object, []string)
	want (sets.Set[string], "k8s.io/apimachinery/pkg/runtime".Object, "k8s.io/apimachinery/pkg/runtime".Object, ...string)
```

**Comment by thockin** [comment]
Passing `sets.Set[string]{}` to those compiles but fails to run:

```
/$ go test ./pkg/apis/core/validation
--- FAIL: TestValidateReplicationController (0.00s)
    validation.go:58: no kind is registered for the type core.ReplicationController in scheme "kubernetes/pkg/api/legacyscheme/scheme.go:30"
W1209 16:05:29.779216  650362 feature_gate.go:354] Setting GA feature gate PodHostIPs=true. It will be removed in a future release.
FAIL
FAIL	k8s.io/kubernetes/pkg/apis/core/validation	0.215s
FAIL
```

I'm not sure which piece of magic is missing, and I wonder if there's a less magical approach :)

**Comment by thockin** [comment]
My diff:


```diff
diff --git a/pkg/apis/core/validation/validation_test.go b/pkg/apis/core/validation/validation_test.go
index 03952109a93..4fe7c6ee85a 100644
--- a/pkg/apis/core/validation/validation_test.go
+++ b/pkg/apis/core/validation/validation_test.go
@@ -37,6 +37,7 @@ import (
        v1 "k8s.io/api/core/v1"
        "k8s.io/apimachinery/pkg/api/resource"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+       runtimetesting "k8s.io/apimachinery/pkg/runtime/testing"
        "k8s.io/apimachinery/pkg/util/intstr"
        "k8s.io/apimachinery/pkg/util/sets"
        "k8s.io/apimachinery/pkg/util/validation"
@@ -16559,9 +16560,15 @@ func TestValidateReplicationController(t *testing.T) {
                mkValidReplicationController(func(rc *core.ReplicationController) { rc.Spec.Replicas = 100 }),
        }
        for _, tc := range successCases {
-               if errs := ValidateReplicationController(&tc, PodValidationOptions{}); len(errs) != 0 {
-                       t.Errorf("expected success: %v", errs)
-               }
+               runtimetesting.RunValidationForEachVersion(t, &tc, func(t *testing.T, versionValidationErrors field.ErrorList) {
+                       // Continue to run handwritten validation until migration to declarative validation is complete.
+                       errs := ValidateReplicationController(&tc, PodValidationOptions{})
+                       // Run declarative validation for the version
+                       errs = append(errs, versionValidationErrors...)
+                       if len(errs) != 0 {
+                               t.Errorf("expected success: %v", errs)
+                       }
+               })
        }
 
        fmtErrs := func(errs field.ErrorList) string {
```

**Comment by jpbetz** [comment]
> Passing `sets.Set[string]{}` to those compiles but fails to run:
> 
> ```
> /$ go test ./pkg/apis/core/validation
> --- FAIL: TestValidateReplicationController (0.00s)
>     validation.go:58: no kind is registered for the type core.ReplicationController in scheme "kubernetes/pkg/api/legacyscheme/scheme.go:30"
> W1209 16:05:29.779216  650362 feature_gate.go:354] Setting GA feature gate PodHostIPs=true. It will be removed in a future release.
> FAIL
> FAIL	k8s.io/kubernetes/pkg/apis/core/validation	0.215s
> FAIL
> ```

Ah, we added options after dropping this code.  The reason the run fails is that the legacy scheme must be registered using an import like `_ "k8s.io/kubernetes/pkg/apis/apps/install"`.

> I'm not sure which piece of magic is missing, and I wonder if there's a less magical approach :)

Options I can think of :

- Call the versioned validator directly.
- Put the validation on unversioned code and then call that from somewhere (ideally the strategies) such that the tests "just work".

**Comment by jpbetz** [comment]
I've pushed code to add the options args.

**Comment by thockin** [comment]
I patched this in and added the `_ "k8s.io/kubernetes/pkg/apis/apps/install"` import, and it works.  I can prove that the test works.  That said, we need to decide how we want to do this testing, especially in the face of potentially multiple versions.

The way I hacked it up, it proves that:
* the old (internal version) validates the field
* the existing validation fails ("expected error") when the manual validation is removed
* the existing validation succeeds again when the autogenerated validation is added

If there are 2 versions, this does not work (we'll get 2 errors for 2 versions) and does not verify equivalent errors across versions.

discuss...

**Comment by thockin** [comment]
The way I was approaching testing was different than what you describe.  I was trying to prove that the _removal of manual validation_ is safe.
* test(manual) passes
* remove manual validation
* test(manual) fails
* test(manual+generated) passes

> One option might be to simply test one version like we do today, and then have a utility that checks that all versions produce the exact same errors.

Right.  Before I started to write that, I felt we had to have the discussion about versioned vs. internal, and about how we intend to incrementally enable this.  It makes a big difference in how we approach the transition and testing.

WRT transition: Do we expect to put a feature gate on these?  When does that go away?  The transition could take many releases and I think we need to spread the risk out.  How? 

Option: Incrementally add new tags and generate code, leave manual code. Call generated code XOR manual code, based on a feature gate. We cannot enable the gate by default until EVERYTHING is converted (or we break it into several gates). This will back-load most of the risk.

Option: Incrementally add new tags and generate code, leave manual code. Call generated code AND manual code. This will incrementally expose us to false-fails (rejecting something that used to be allowed) but any false-passes (allowing something we used to reject) will not be exposed until manual code is removed (back-loading some risk).

Option: Incrementally add new tags and generate code, remove manual code.  Call generated code AND manual code. This will incrementally expose us to false-fails (rejecting something that used to be allowed) and false-passes (allowing something we used to reject).

**Comment by thockin** [comment]
Gonna merge this, sinc eit seems OK no matter which path :)

**Pull request merged**
